// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-transport-requests.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-transport-requests.ts
var list_transport_requests_default = defineTool({
  name: "list_transport_requests",
  title: "Listar pedidos de transporte",
  description: "Lista os pedidos de transporte vis\xEDveis para o utilizador autenticado, com filtro opcional por estado.",
  inputSchema: {
    status: z.string().optional().describe("Filtrar por estado, ex: pending, accepted, in_transit, completed."),
    limit: z.number().int().optional().describe("N\xFAmero m\xE1ximo de resultados (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("transport_requests").select(
      "id,title,cargo_type,weight_kg,origin_address,destination_address,pickup_date,status,created_at"
    ).order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/create-transport-request.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_transport_request_default = defineTool2({
  name: "create_transport_request",
  title: "Criar pedido de transporte",
  description: "Cria um novo pedido de transporte para a cooperativa autenticada.",
  inputSchema: {
    title: z2.string().describe("T\xEDtulo curto do pedido."),
    cargo_type: z2.string().describe("Tipo de carga, ex: milho, arroz, castanha de caju."),
    origin_address: z2.string().describe("Endere\xE7o de origem (distrito/prov\xEDncia)."),
    destination_address: z2.string().describe("Endere\xE7o de destino."),
    pickup_date: z2.string().describe("Data de recolha no formato YYYY-MM-DD."),
    weight_kg: z2.number().optional().describe("Peso da carga em quilogramas."),
    description: z2.string().optional().describe("Detalhes adicionais do pedido.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("transport_requests").insert({ ...input, cooperative_id: ctx.getUserId(), status: "pending" }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-proposals.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_proposals_default = defineTool3({
  name: "list_proposals",
  title: "Listar propostas",
  description: "Lista as propostas de transporte vis\xEDveis para o utilizador autenticado, opcionalmente filtradas por pedido.",
  inputSchema: {
    transport_request_id: z3.string().optional().describe("ID do pedido de transporte."),
    limit: z3.number().int().optional().describe("N\xFAmero m\xE1ximo de resultados (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ transport_request_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("transport_proposals").select("id,transport_request_id,price,description,status,created_at").order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (transport_request_id) query = query.eq("transport_request_id", transport_request_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-fleet-vehicles.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_fleet_vehicles_default = defineTool4({
  name: "list_fleet_vehicles",
  title: "Listar viaturas da frota",
  description: "Lista as viaturas registadas na frota da transportadora autenticada.",
  inputSchema: {
    limit: z4.number().int().optional().describe("N\xFAmero m\xE1ximo de resultados (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("fleet_vehicles").select("id,plate,brand,model,vehicle_type,capacity_kg,year,status,created_at").order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 100));
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/index.ts
var projectRef = "xnrckjigfltaaanzfzml";
var mcp_default = defineMcp({
  name: "mova-agro-mcp",
  title: "MOVA AGRO",
  version: "0.1.0",
  instructions: "Ferramentas da plataforma MOVA AGRO (log\xEDstica agr\xEDcola em Mo\xE7ambique). Permite listar e criar pedidos de transporte, consultar propostas e ver as viaturas da frota do utilizador autenticado. Valores monet\xE1rios em MZN.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_transport_requests_default, create_transport_request_default, list_proposals_default, list_fleet_vehicles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
